### PR TITLE
Added 2 missing people

### PR DESCRIPTION
**Pull request by 1alphabyte**
Hi there
I have added the 2 missing people I saw ik there are 3, but I can't seem to find the last one
And I also fixed my recording to use it in the intended way.

### CODE REVIEW

**Comment by DeveshSenthilraja** [comment]
Hello,
I have merged your pull request along with my project. You should see the
changes once the build and deployment process completes.

Kind regard,
Devesh

**Comment by 1alphabyte** [comment]
Umnmmmmm the PR is still open, not merged
And now there are Merge conflicts

**Comment by DeveshSenthilraja** [comment]
No... I mean that I have reviewed the changes that you requested and added them my self

Also, I did take a recording of your recording because Mr.Oswalt said that he only wanted the output
I hope you are okay with that

**Comment by 1alphabyte** [comment]
Alr but thats not what merging the PR mean 
but sure

**Comment by DeveshSenthilraja** [comment]
Well... I wanted to resize some of the recordings, so I didn't go and merge the PR. Instead, I took some new ScreenRecs and made some changes to the video dimentions

**Comment by 1alphabyte** [comment]
Ya sure but just wanted to say i wanted mine like it was because of the space theme that background is a photo from JWT so its ment to go with the theme 
Anyways it doesn't matter and btw good job with the website, and thanks for making it rlly good for such short notice

**Pull request closed without merging**
